function plotObstacles(gridMap)
    [obsRows, obsCols] = find(gridMap == 1);
    plot(obsCols, obsRows, 'ks', ...
         'MarkerFaceColor', 'k', ...
         'MarkerSize', 5, ...
         'DisplayName', 'Obstacles');
end